# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XNIV1ytzpl72Vslg0cWgpIPOfYQkJ6vr
"""

num = int(input(''))

sum_digits = 0

while num > 0:
  digits = num % 10
  sum_digits += digits ** 3
  num //= 10
if sum_digits == num:
  print('your number is  armstrong')
else:
  print('your number is not armstrong')