# -*- coding: utf-8 -*-
"""ID assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pleSL-_oFwjScbMkZehk86XWRvcusbTw
"""

user_name = "arasrabia"
password = "R12345@"

if (user_name and password) == password:
  print(f'Hello {user_name}! your password is {password}')
else:
  print(f"Hello, zeynep! See you later.")