# -*- coding: utf-8 -*-
"""palindromic number

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EPZIOseEK8677XLoG8K4rBpcdmHl8XkC
"""

### find palindromic number
palindrome = []

for i in range(100, 1000):
  for j in range(100, 1000):
    result = i*j
    if str(result) == str(result)[::-1]:
      palindrome.append(result)
print(max(palindrome))