# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XNIV1ytzpl72Vslg0cWgpIPOfYQkJ6vr
"""

# What is prime number? are numbers that can only be divided by themselves and 1.

prime_list = []
for num in range(2, 100):
  for i in range(2, num):
    if num % i == 0:
       break
  else:
       prime_list.append(num)
print(prime_list)
