# -*- coding: utf-8 -*-
"""risk grup assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pleSL-_oFwjScbMkZehk86XWRvcusbTw
"""

age = bool(input('Are you a cigarette addict older than 75 years old? : '))
chronic = bool(input('Do you have a severe chronic disease? :'))
immune = bool(input('Is your immune system too weak? : '))

if (age and chronic and immune) == True:
  print("You are in risky group")
else:
  print("You are not in risky group")